create extension if not exists pgcrypto;

create table if not exists public.procurement_requests (
  procurement_id text primary key,
  vehicle_brand text not null default '',
  vehicle_model text not null default '',
  quantity integer not null default 1,
  supplier_name text,
  supplier_country text,
  estimated_purchase_cost numeric(14, 2) not null default 0,
  estimated_freight_cost numeric(14, 2) not null default 0,
  requested_by text,
  status text not null default 'Draft',
  notes text,
  supplier_id uuid,
  item_type text default 'Vehicle',
  unit_buy_price numeric(14, 2) default 0,
  approved_purchase_amount numeric(14, 2) default 0,
  currency text default 'INR',
  linked_order_id uuid,
  expected_delivery_date date,
  actual_delivery_date date,
  payment_status text default 'Unpaid',
  priority text default 'Medium',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.procurement_orders (
  id uuid primary key default gen_random_uuid(),
  procurement_number text,
  supplier_id uuid,
  item_type text not null default 'Vehicle',
  item_name text not null default '',
  vehicle_brand text,
  vehicle_model text,
  quantity integer not null default 1,
  unit_buy_price numeric(14, 2) not null default 0,
  total_buy_price numeric(14, 2) not null default 0,
  currency text not null default 'INR',
  linked_order_id uuid,
  expected_delivery_date date,
  actual_delivery_date date,
  payment_status text not null default 'Unpaid',
  status text not null default 'Draft',
  priority text not null default 'Medium',
  notes text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
