create table if not exists vehicles (
  id text primary key,
  brand text not null,
  model text not null,
  category text not null,
  quantity integer not null default 0,
  purchase_price numeric(12, 2) not null default 0,
  selling_price numeric(12, 2) not null default 0,
  status text not null default 'Available',
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists customers (
  id text primary key,
  name text not null,
  phone text,
  email text,
  location text,
  notes text,
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id text primary key,
  customer_name text not null,
  vehicle text not null,
  quantity integer not null default 1,
  order_date date not null default current_date,
  purchase_cost numeric(12, 2) not null default 0,
  selling_price numeric(12, 2) not null default 0,
  status text not null default 'Inquiry',
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists shipments (
  shipment_id text primary key,
  linked_order_id text,
  customer_name text not null,
  vehicle text not null,
  quantity integer not null default 1,
  destination_country text not null,
  port_of_departure text,
  port_of_arrival text,
  shipping_company text,
  freight_cost numeric(12, 2) not null default 0,
  eta date,
  status text not null default 'Preparing',
  notes text,
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists order_timeline_events (
  id bigint generated by default as identity primary key,
  order_id text not null,
  status text not null,
  note text,
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table vehicles add column if not exists created_by uuid default auth.uid() references auth.users(id) on delete cascade;
alter table customers add column if not exists created_by uuid default auth.uid() references auth.users(id) on delete cascade;
alter table orders add column if not exists created_by uuid default auth.uid() references auth.users(id) on delete cascade;
alter table shipments add column if not exists created_by uuid default auth.uid() references auth.users(id) on delete cascade;
alter table order_timeline_events add column if not exists created_by uuid default auth.uid() references auth.users(id) on delete cascade;

alter table vehicles enable row level security;
alter table customers enable row level security;
alter table orders enable row level security;
alter table shipments enable row level security;
alter table order_timeline_events enable row level security;

drop policy if exists "Allow anon read vehicles" on vehicles;
drop policy if exists "Allow anon insert vehicles" on vehicles;
drop policy if exists "Allow anon update vehicles" on vehicles;
drop policy if exists "Allow anon delete vehicles" on vehicles;
drop policy if exists "Users can read own vehicles" on vehicles;
drop policy if exists "Users can insert own vehicles" on vehicles;
drop policy if exists "Users can update own vehicles" on vehicles;
drop policy if exists "Users can delete own vehicles" on vehicles;

create policy "Users can read own vehicles"
on vehicles for select
to authenticated
using (created_by = auth.uid());

create policy "Users can insert own vehicles"
on vehicles for insert
to authenticated
with check (created_by = auth.uid());

create policy "Users can update own vehicles"
on vehicles for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

create policy "Users can delete own vehicles"
on vehicles for delete
to authenticated
using (created_by = auth.uid());

drop policy if exists "Allow anon read customers" on customers;
drop policy if exists "Allow anon insert customers" on customers;
drop policy if exists "Allow anon update customers" on customers;
drop policy if exists "Allow anon delete customers" on customers;
drop policy if exists "Users can read own customers" on customers;
drop policy if exists "Users can insert own customers" on customers;
drop policy if exists "Users can update own customers" on customers;
drop policy if exists "Users can delete own customers" on customers;

create policy "Users can read own customers"
on customers for select
to authenticated
using (created_by = auth.uid());

create policy "Users can insert own customers"
on customers for insert
to authenticated
with check (created_by = auth.uid());

create policy "Users can update own customers"
on customers for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

create policy "Users can delete own customers"
on customers for delete
to authenticated
using (created_by = auth.uid());

drop policy if exists "Allow anon read orders" on orders;
drop policy if exists "Allow anon insert orders" on orders;
drop policy if exists "Allow anon update orders" on orders;
drop policy if exists "Allow anon delete orders" on orders;
drop policy if exists "Users can read own orders" on orders;
drop policy if exists "Users can insert own orders" on orders;
drop policy if exists "Users can update own orders" on orders;
drop policy if exists "Users can delete own orders" on orders;

create policy "Users can read own orders"
on orders for select
to authenticated
using (created_by = auth.uid());

create policy "Users can insert own orders"
on orders for insert
to authenticated
with check (created_by = auth.uid());

create policy "Users can update own orders"
on orders for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

create policy "Users can delete own orders"
on orders for delete
to authenticated
using (created_by = auth.uid());

drop policy if exists "Users can read own shipments" on shipments;
drop policy if exists "Users can insert own shipments" on shipments;
drop policy if exists "Users can update own shipments" on shipments;
drop policy if exists "Users can delete own shipments" on shipments;

create policy "Users can read own shipments"
on shipments for select
to authenticated
using (created_by = auth.uid());

create policy "Users can insert own shipments"
on shipments for insert
to authenticated
with check (created_by = auth.uid());

create policy "Users can update own shipments"
on shipments for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

create policy "Users can delete own shipments"
on shipments for delete
to authenticated
using (created_by = auth.uid());

drop policy if exists "Users can read own order timeline events" on order_timeline_events;
drop policy if exists "Users can insert own order timeline events" on order_timeline_events;
drop policy if exists "Users can update own order timeline events" on order_timeline_events;
drop policy if exists "Users can delete own order timeline events" on order_timeline_events;

create policy "Users can read own order timeline events"
on order_timeline_events for select
to authenticated
using (created_by = auth.uid());

create policy "Users can insert own order timeline events"
on order_timeline_events for insert
to authenticated
with check (created_by = auth.uid());

create policy "Users can update own order timeline events"
on order_timeline_events for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

create policy "Users can delete own order timeline events"
on order_timeline_events for delete
to authenticated
using (created_by = auth.uid());
