create table if not exists vehicles (
  id text primary key,
  brand text not null,
  model text not null,
  category text not null,
  quantity integer not null default 0,
  purchase_price numeric(12, 2) not null default 0,
  selling_price numeric(12, 2) not null default 0,
  status text not null default 'Available',
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists customers (
  id text primary key,
  name text not null,
  phone text,
  email text,
  location text,
  notes text,
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null,
  customer_name text not null,
  vehicle text not null,
  quantity integer not null default 1,
  order_date date not null default current_date,
  purchase_cost numeric(12, 2) not null default 0,
  selling_price numeric(12, 2) not null default 0,
  status text not null default 'Inquiry',
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists shipments (
  shipment_id text primary key,
  linked_order_id uuid references orders(id) on delete set null,
  customer_name text not null,
  vehicle text not null,
  quantity integer not null default 1,
  destination_country text not null,
  port_of_departure text,
  port_of_arrival text,
  shipping_company text,
  freight_cost numeric(12, 2) not null default 0,
  eta date,
  status text not null default 'Preparing',
  notes text,
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists order_timeline_events (
  id bigint generated by default as identity primary key,
  order_id uuid not null references orders(id) on delete cascade,
  status text not null,
  note text,
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table vehicles add column if not exists created_by uuid default auth.uid() references auth.users(id) on delete cascade;
alter table customers add column if not exists created_by uuid default auth.uid() references auth.users(id) on delete cascade;
alter table orders add column if not exists created_by uuid default auth.uid() references auth.users(id) on delete cascade;
alter table orders add column if not exists order_number text;
update orders set order_number = id::text where order_number is null or order_number = '';
alter table shipments add column if not exists created_by uuid default auth.uid() references auth.users(id) on delete cascade;
alter table order_timeline_events add column if not exists created_by uuid default auth.uid() references auth.users(id) on delete cascade;

-- If your existing orders.id column is still text and contains display numbers like '0001',
-- run this one-time migration in Supabase before using UUID-linked timelines/shipments:
--
-- alter table order_timeline_events drop constraint if exists order_timeline_events_order_id_fkey;
-- alter table shipments drop constraint if exists shipments_linked_order_id_fkey;
-- alter table orders rename column id to legacy_order_id;
-- alter table orders add column id uuid default gen_random_uuid();
-- update orders set order_number = legacy_order_id where order_number is null or order_number = '';
-- alter table orders drop constraint orders_pkey;
-- alter table orders add constraint orders_pkey primary key (id);
-- alter table shipments add column if not exists linked_order_uuid uuid;
-- update shipments s set linked_order_uuid = o.id from orders o where s.linked_order_id::text = o.legacy_order_id;
-- alter table shipments drop column linked_order_id;
-- alter table shipments rename column linked_order_uuid to linked_order_id;
-- alter table shipments add constraint shipments_linked_order_id_fkey foreign key (linked_order_id) references orders(id) on delete set null;
-- alter table order_timeline_events add column if not exists order_uuid uuid;
-- update order_timeline_events e set order_uuid = o.id from orders o where e.order_id::text = o.legacy_order_id;
-- alter table order_timeline_events drop column order_id;
-- alter table order_timeline_events rename column order_uuid to order_id;
-- alter table order_timeline_events add constraint order_timeline_events_order_id_fkey foreign key (order_id) references orders(id) on delete cascade;

alter table vehicles enable row level security;
alter table customers enable row level security;
alter table orders enable row level security;
alter table shipments enable row level security;
alter table order_timeline_events enable row level security;

drop policy if exists "Allow anon read vehicles" on vehicles;
drop policy if exists "Allow anon insert vehicles" on vehicles;
drop policy if exists "Allow anon update vehicles" on vehicles;
drop policy if exists "Allow anon delete vehicles" on vehicles;
drop policy if exists "Users can read own vehicles" on vehicles;
drop policy if exists "Users can insert own vehicles" on vehicles;
drop policy if exists "Users can update own vehicles" on vehicles;
drop policy if exists "Users can delete own vehicles" on vehicles;

create policy "Users can read own vehicles"
on vehicles for select
to authenticated
using (created_by = auth.uid());

create policy "Users can insert own vehicles"
on vehicles for insert
to authenticated
with check (created_by = auth.uid());

create policy "Users can update own vehicles"
on vehicles for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

create policy "Users can delete own vehicles"
on vehicles for delete
to authenticated
using (created_by = auth.uid());

drop policy if exists "Allow anon read customers" on customers;
drop policy if exists "Allow anon insert customers" on customers;
drop policy if exists "Allow anon update customers" on customers;
drop policy if exists "Allow anon delete customers" on customers;
drop policy if exists "Users can read own customers" on customers;
drop policy if exists "Users can insert own customers" on customers;
drop policy if exists "Users can update own customers" on customers;
drop policy if exists "Users can delete own customers" on customers;

create policy "Users can read own customers"
on customers for select
to authenticated
using (created_by = auth.uid());

create policy "Users can insert own customers"
on customers for insert
to authenticated
with check (created_by = auth.uid());

create policy "Users can update own customers"
on customers for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

create policy "Users can delete own customers"
on customers for delete
to authenticated
using (created_by = auth.uid());

drop policy if exists "Allow anon read orders" on orders;
drop policy if exists "Allow anon insert orders" on orders;
drop policy if exists "Allow anon update orders" on orders;
drop policy if exists "Allow anon delete orders" on orders;
drop policy if exists "Users can read own orders" on orders;
drop policy if exists "Users can insert own orders" on orders;
drop policy if exists "Users can update own orders" on orders;
drop policy if exists "Users can delete own orders" on orders;

create policy "Users can read own orders"
on orders for select
to authenticated
using (created_by = auth.uid());

create policy "Users can insert own orders"
on orders for insert
to authenticated
with check (created_by = auth.uid());

create policy "Users can update own orders"
on orders for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

create policy "Users can delete own orders"
on orders for delete
to authenticated
using (created_by = auth.uid());

drop policy if exists "Users can read own shipments" on shipments;
drop policy if exists "Users can insert own shipments" on shipments;
drop policy if exists "Users can update own shipments" on shipments;
drop policy if exists "Users can delete own shipments" on shipments;

create policy "Users can read own shipments"
on shipments for select
to authenticated
using (created_by = auth.uid());

create policy "Users can insert own shipments"
on shipments for insert
to authenticated
with check (created_by = auth.uid());

create policy "Users can update own shipments"
on shipments for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

create policy "Users can delete own shipments"
on shipments for delete
to authenticated
using (created_by = auth.uid());

drop policy if exists "Users can read own order timeline events" on order_timeline_events;
drop policy if exists "Users can insert own order timeline events" on order_timeline_events;
drop policy if exists "Users can update own order timeline events" on order_timeline_events;
drop policy if exists "Users can delete own order timeline events" on order_timeline_events;

create policy "Users can read own order timeline events"
on order_timeline_events for select
to authenticated
using (created_by = auth.uid());

create policy "Users can insert own order timeline events"
on order_timeline_events for insert
to authenticated
with check (created_by = auth.uid());

create policy "Users can update own order timeline events"
on order_timeline_events for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

create policy "Users can delete own order timeline events"
on order_timeline_events for delete
to authenticated
using (created_by = auth.uid());

-- Phase 2 enterprise operations additions.
-- Safe and non-destructive: creates new support tables and adds optional columns only.

create table if not exists locations (
  name text primary key,
  department text,
  notes text,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

insert into locations (name, department, notes)
values
  ('Seoul HQ', 'Management', 'Executive operations and administration'),
  ('New City Showroom', 'Sales', 'Retail and customer-facing sales operations'),
  ('Port Operations Office', 'Logistics', 'Freight, customs, and port coordination'),
  ('Warehouse', 'Inventory', 'Vehicle storage and inventory handling')
on conflict (name) do nothing;

create table if not exists departments (
  name text primary key,
  description text,
  created_at timestamptz not null default now()
);

insert into departments (name, description)
values
  ('Sales', 'Customer, deal, and order operations'),
  ('Inventory', 'Vehicle stock, pricing, and availability'),
  ('Logistics', 'Shipment, port, freight, and delivery workflow'),
  ('Finance', 'Revenue, profit, freight cost, and reporting'),
  ('Management', 'Executive oversight, audit logs, and controls')
on conflict (name) do nothing;

create table if not exists alerts (
  id uuid primary key default gen_random_uuid(),
  alert_type text not null,
  severity text not null check (severity in ('Low', 'Medium', 'High', 'Critical')),
  title text not null,
  message text not null,
  linked_module text,
  linked_record_id text,
  resolved boolean not null default false,
  created_by uuid default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table vehicles add column if not exists location_name text default 'Seoul HQ';
alter table vehicles add column if not exists department text default 'Inventory';
alter table orders add column if not exists location_name text default 'Seoul HQ';
alter table orders add column if not exists department text default 'Sales';
alter table customers add column if not exists department text default 'Sales';
alter table shipments add column if not exists location_name text default 'Port Operations Office';
alter table shipments add column if not exists department text default 'Logistics';

alter table locations enable row level security;
alter table departments enable row level security;
alter table alerts enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'locations' and policyname = 'Users can read locations') then
    create policy "Users can read locations" on locations for select to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'locations' and policyname = 'Users can manage own locations') then
    create policy "Users can manage own locations" on locations for all to authenticated using (created_by = auth.uid() or created_by is null) with check (created_by = auth.uid() or created_by is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'departments' and policyname = 'Users can read departments') then
    create policy "Users can read departments" on departments for select to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'alerts' and policyname = 'Users can read own alerts') then
    create policy "Users can read own alerts" on alerts for select to authenticated using (created_by = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'alerts' and policyname = 'Users can insert own alerts') then
    create policy "Users can insert own alerts" on alerts for insert to authenticated with check (created_by = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'alerts' and policyname = 'Users can update own alerts') then
    create policy "Users can update own alerts" on alerts for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());
  end if;
end $$;

-- Role-based access control additions.
-- Safe and non-destructive: creates profiles and additive policies only.

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  role text not null default 'Inventory Manager' check (role in ('CEO', 'Company Manager', 'Logistics Manager', 'Inventory Manager', 'Finance Manager')),
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_one_ceo
on profiles (role)
where role = 'CEO';

create unique index if not exists profiles_one_company_manager
on profiles (role)
where role = 'Company Manager';

alter table profiles enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can read own profile') then
    create policy "Users can read own profile" on profiles for select to authenticated using (id = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can insert own profile') then
    create policy "Users can insert own profile" on profiles for insert to authenticated with check (id = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'vehicles' and policyname = 'Role read vehicles') then
    create policy "Role read vehicles" on vehicles for select to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager', 'Finance Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'vehicles' and policyname = 'Role manage vehicles') then
    create policy "Role manage vehicles" on vehicles for all to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager'))
    ) with check (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'orders' and policyname = 'Role read orders') then
    create policy "Role read orders" on orders for select to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Logistics Manager', 'Finance Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'orders' and policyname = 'Role manage orders') then
    create policy "Role manage orders" on orders for all to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager'))
    ) with check (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'customers' and policyname = 'Role read customers') then
    create policy "Role read customers" on customers for select to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Finance Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'customers' and policyname = 'Role manage customers') then
    create policy "Role manage customers" on customers for all to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager'))
    ) with check (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'shipments' and policyname = 'Role read shipments') then
    create policy "Role read shipments" on shipments for select to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Logistics Manager', 'Finance Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'shipments' and policyname = 'Role manage shipments') then
    create policy "Role manage shipments" on shipments for all to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Logistics Manager'))
    ) with check (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Logistics Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'order_timeline_events' and policyname = 'Role read order timeline events') then
    create policy "Role read order timeline events" on order_timeline_events for select to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Logistics Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'order_timeline_events' and policyname = 'Role manage order timeline events') then
    create policy "Role manage order timeline events" on order_timeline_events for all to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Logistics Manager'))
    ) with check (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Logistics Manager'))
    );
  end if;
end $$;

-- To make your existing signed-in account CEO manually:
-- update profiles set role = 'CEO' where email = 'your-email@example.com';

-- Procurement module additions.
-- Safe and non-destructive: new tables and additive policies only.

create table if not exists suppliers (
  id uuid primary key default gen_random_uuid(),
  supplier_name text not null,
  country text,
  contact_person text,
  phone text,
  email text,
  notes text,
  created_by uuid default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists procurement_requests (
  procurement_id text primary key,
  vehicle_brand text not null,
  vehicle_model text not null,
  quantity integer not null default 1,
  supplier_name text,
  supplier_country text,
  estimated_purchase_cost numeric(14, 2) not null default 0,
  estimated_freight_cost numeric(14, 2) not null default 0,
  requested_by text,
  status text not null default 'Requested',
  notes text,
  created_by uuid default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists procurement_timeline (
  id bigint generated by default as identity primary key,
  procurement_id text not null references procurement_requests(procurement_id) on delete cascade,
  status text not null,
  note text,
  created_by uuid default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table suppliers enable row level security;
alter table procurement_requests enable row level security;
alter table procurement_timeline enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'suppliers' and policyname = 'Role read suppliers') then
    create policy "Role read suppliers" on suppliers for select to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager', 'Finance Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'suppliers' and policyname = 'Role manage suppliers') then
    create policy "Role manage suppliers" on suppliers for all to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager'))
    ) with check (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'procurement_requests' and policyname = 'Role read procurement requests') then
    create policy "Role read procurement requests" on procurement_requests for select to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager', 'Finance Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'procurement_requests' and policyname = 'Role manage procurement requests') then
    create policy "Role manage procurement requests" on procurement_requests for all to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager'))
    ) with check (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'procurement_timeline' and policyname = 'Role read procurement timeline') then
    create policy "Role read procurement timeline" on procurement_timeline for select to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager', 'Finance Manager'))
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'procurement_timeline' and policyname = 'Role manage procurement timeline') then
    create policy "Role manage procurement timeline" on procurement_timeline for all to authenticated using (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager'))
    ) with check (
      exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('CEO', 'Company Manager', 'Inventory Manager'))
    );
  end if;
end $$;
